### ISSUE TITLE
running an app in iframe,refresh the app  will call twice method

### ISSUE THREAD

**Issue by alexanderkenndy** [intel/web-simulator#396]
I have an app in iframe running with websimulator,the app is as follows:

function test(){
alert('demo');

body onload="test()"

when I refresh this app,the alert method will execute twice,and I couldn't find this bug.wish for your help

**Comment by wcwang** [comment]
This is not your application's bug. The Ripple framework will load the application in iframe twice. It should be OK to ignore the first one.

**Comment by alexanderkenndy** [comment]
@wcwang  thank you for reply and I have found the position,and comment it in bootstrap.js,we all know it's good,but our app developer thgought it was a bug.Hmm,whatever I agree with you
